Document: vulkan-headers
Title: Debian vulkan-headers Manual
Author: <insert document author here>
Abstract: This manual describes what vulkan-headers is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/vulkan-headers/vulkan-headers.sgml.gz

Format: postscript
Files: /usr/share/doc/vulkan-headers/vulkan-headers.ps.gz

Format: text
Files: /usr/share/doc/vulkan-headers/vulkan-headers.text.gz

Format: HTML
Index: /usr/share/doc/vulkan-headers/html/index.html
Files: /usr/share/doc/vulkan-headers/html/*.html
